# -*- coding: utf-8 -*-
"""
Created on Thu Nov 20 16:06:16 2025

@author: JP
"""

from command_dict import command_dict

def parse_command(command_string):
    """
    Parses a command string and returns a tuple with the full subsystem name,
    the command description, and the parameter value.
    """
    """
    The following code was generated by ChatGPT with the prompt:
    "How to pull function names from the command dictionary given the file?"
    Modifications to this have been made to better align to overall program goals
    """
    
    #Split the input based on the : delimiter 
    subsysCode, cmd, cmdValue = command_string.split(":")
    
    #Call helper function to parse the dictionary
    subsystemName, subsystemData = findSubsystemByCode(subsysCode)
    
    #If it didn't find it, raise an error
    if subsystemData is None:
        raise KeyError(f"Unknown subsystem code: {subsysCode}")
    
    #If this command isn't one that's known, raise an error
    if cmd not in subsystemData["Commands"]:
        raise KeyError(f"Unknown command: {cmd}")
    
    #Actually grab the function name
    funcName = subsystemData["Commands"][cmd][0]
    
    #Command validation bolt-on
    validateCommand(command_string)
    
    
    #Return parsed values
    return (subsystemName, funcName, cmdValue)

def findSubsystemByCode(code):
    for name, data in command_dict.items():   # :contentReference[oaicite:0]{index=0}
        if data["Code"] == code:
            return name, data
    return None, None


#The following helper function was generated by ChatGPT
def validateCommand(commandString):
    # Parse "EPS:CMD01:0"
    try:
        subsysCode, cmdName, cmdArg = commandString.split(":")
    except ValueError:
        raise ValueError("Invalid command format. Expected format: SUBSYS:CMDXX:VALUE")

    # Convert argument to integer
    try:
        cmdArgValue = int(cmdArg)
    except ValueError:
        raise ValueError(f"Command argument must be an integer: '{cmdArg}'")

    # Find subsystem
    subsystemName, subsystemData = findSubsystemByCode(subsysCode)
    if subsystemData is None:
        raise KeyError(f"Unknown subsystem code: {subsysCode}")

    # Verify command exists
    if cmdName not in subsystemData["Commands"]:
        raise KeyError(
            f"Command '{cmdName}' does not exist for subsystem '{subsystemName}'"
        )

    # Extract command info
    funcName, validRange = subsystemData["Commands"][cmdName]

    # Validate argument against allowed range/set
    if not isValueValid(validRange, cmdArgValue):
        raise ValueError(
            f"Invalid value {cmdArgValue} for command '{cmdName}'. "
            f"Expected something in {validRange}."
        )

    # If we reach here, everything is valid
    return {
        "subsystemName": subsystemName,
        "functionName": funcName,
        "commandName": cmdName,
        "value": cmdArgValue
    }

#The following helper function was generated by ChatGPT
def isValueValid(validRange, argValue):
    # validRange can be:
    #   - a set {0,1}
    #   - a range(0, 60)
    if isinstance(validRange, set):
        return argValue in validRange

    if isinstance(validRange, range):
        return argValue in validRange

    raise TypeError(f"Unsupported validation type: {type(validRange)}")

def main():
    """
    Main function to test the command parser.
    """
    
    """
Test commands from Prof McDonald:
    test_commands = [
        "EPS:CMD01:0",
        "ACS:CMD04:-1",
        "RCS:INVALID:0"
    ]  
    """

    #Custom Test Commands
    testCommandsValid = [
    "EPS:CMD01:1",      # EPS, BATTERY_CHARGE_MODE, allowed {0,1}
    "EPS:CMD02:4",      # EPS, POWER_ON_MODULE, allowed {0,1,2,3,4}
    "EPS:CMD04:119",    # EPS, VOLTAGE_SETPOINT, in range(0,120)

    "RCS:CMD01:0",      # RCS, THRUST_X, in range(0,60)
    "RCS:CMD03:59",     # RCS, THRUST_Z, upper edge of range(0,60)
    "RCS:CMD04:1",      # RCS, SAFE_MODE, {0,1}

    "TCS:CMD04:-30",    # TCS, TEMP_SETPOINT, lower edge of range(-30,60)
    "TCS:CMD01:1",      # TCS, HEATER_ON, {0,1}

    "ACS:CMD01:0",      # ACS, ROTATE_X, in range(-360,360)
    "ACS:CMD03:359",    # ACS, ROTATE_Z, high positive bound in range

    "CDH:CMD02:0",      # CDH, TRANSMIT_LOW, {0,1}
    "TTC:CMD03:1",      # TTC, TRACKING_MODE, {0,1}

    "PL1:CMD01:1",      # PL1, START_DATA_ACQUISITION, {0,1}
    "PL2:CMD04:0"       # PL2, SAFE_MODE, {0,1}
    ]

    for cmd in testCommandsValid:
        subsystem, description, value = parse_command(cmd)
        print(f"Command: {cmd}")
        print(f" -> Subsystem: {subsystem}")
        print(f" -> Description: {description}")
        print(f" -> Value: {value}")
        print("-" * 20)

if __name__ == "__main__":
    main()
